// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, is_admin, is_owner)
VALUES (?, ?, ?, ?, ?)
RETURNING id, username, email, password_hash, created_at, updated_at, is_admin, is_owner, session_invalidated_at, subscription_type, subscription_expires_at, subscription_warning_enabled, subscription_warning_message, last_seen_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      bool   `json:"is_admin"`
	IsOwner      bool   `json:"is_owner"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.IsAdmin,
		arg.IsOwner,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.IsOwner,
		&i.SessionInvalidatedAt,
		&i.SubscriptionType,
		&i.SubscriptionExpiresAt,
		&i.SubscriptionWarningEnabled,
		&i.SubscriptionWarningMessage,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, created_at, updated_at, is_admin, is_owner, session_invalidated_at, subscription_type, subscription_expires_at, subscription_warning_enabled, subscription_warning_message, last_seen_at FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.IsOwner,
		&i.SessionInvalidatedAt,
		&i.SubscriptionType,
		&i.SubscriptionExpiresAt,
		&i.SubscriptionWarningEnabled,
		&i.SubscriptionWarningMessage,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, created_at, updated_at, is_admin, is_owner, session_invalidated_at, subscription_type, subscription_expires_at, subscription_warning_enabled, subscription_warning_message, last_seen_at FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.IsOwner,
		&i.SessionInvalidatedAt,
		&i.SubscriptionType,
		&i.SubscriptionExpiresAt,
		&i.SubscriptionWarningEnabled,
		&i.SubscriptionWarningMessage,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, created_at, updated_at, is_admin, is_owner, session_invalidated_at, subscription_type, subscription_expires_at, subscription_warning_enabled, subscription_warning_message, last_seen_at FROM users
WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.IsOwner,
		&i.SessionInvalidatedAt,
		&i.SubscriptionType,
		&i.SubscriptionExpiresAt,
		&i.SubscriptionWarningEnabled,
		&i.SubscriptionWarningMessage,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserSessionInvalidatedAt = `-- name: GetUserSessionInvalidatedAt :one
SELECT session_invalidated_at FROM users
WHERE id = ?
`

func (q *Queries) GetUserSessionInvalidatedAt(ctx context.Context, id int64) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getUserSessionInvalidatedAt, id)
	var session_invalidated_at sql.NullTime
	err := row.Scan(&session_invalidated_at)
	return session_invalidated_at, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = ?, email = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, username, email, password_hash, created_at, updated_at, is_admin, is_owner, session_invalidated_at, subscription_type, subscription_expires_at, subscription_warning_enabled, subscription_warning_message, last_seen_at
`

type UpdateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Username, arg.Email, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.IsOwner,
		&i.SessionInvalidatedAt,
		&i.SubscriptionType,
		&i.SubscriptionExpiresAt,
		&i.SubscriptionWarningEnabled,
		&i.SubscriptionWarningMessage,
		&i.LastSeenAt,
	)
	return i, err
}

const updateUserSessionInvalidatedAt = `-- name: UpdateUserSessionInvalidatedAt :exec
UPDATE users
SET session_invalidated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateUserSessionInvalidatedAt(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUserSessionInvalidatedAt, id)
	return err
}

const updateUserSubscription = `UPDATE users SET subscription_type = ?, subscription_expires_at = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?`

type UpdateUserSubscriptionParams struct {
	SubscriptionType      string       `json:"subscription_type"`
	SubscriptionExpiresAt sql.NullTime `json:"subscription_expires_at"`
	ID                    int64        `json:"id"`
}

func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSubscription, arg.SubscriptionType, arg.SubscriptionExpiresAt, arg.ID)
	return err
}

const updateUserSubscriptionWarning = `UPDATE users SET subscription_warning_enabled = ?, subscription_warning_message = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?`

type UpdateUserSubscriptionWarningParams struct {
	SubscriptionWarningEnabled bool   `json:"subscription_warning_enabled"`
	SubscriptionWarningMessage string `json:"subscription_warning_message"`
	ID                         int64  `json:"id"`
}

func (q *Queries) UpdateUserSubscriptionWarning(ctx context.Context, arg UpdateUserSubscriptionWarningParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSubscriptionWarning, arg.SubscriptionWarningEnabled, arg.SubscriptionWarningMessage, arg.ID)
	return err
}

const updateUserLastSeen = `UPDATE users SET last_seen_at = CURRENT_TIMESTAMP WHERE id = ?`

func (q *Queries) UpdateUserLastSeen(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUserLastSeen, id)
	return err
}
